# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH

if [ -d "$HOME/.local/bin" ]; then
    export PATH="$HOME/.local/bin:$PATH";
fi

export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

[[ $TMUX = "" ]] && export TERM="xterm-256color"

ZSH_THEME="powerlevel10k/powerlevel10k"

ZSH_COMMAND_TIME_COLOR="cyan"

# oh-my-zsh settings
DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="false"

# CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"
# export UPDATE_ZSH_DAYS=13
#DISABLE_AUTO_TITLE="true"
# COMPLETION_WAITING_DOTS="true"

plugins=(git common-aliases docker jump command-time zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration
export EDITOR='vim'
export VISUAL='vim'

# history settings
HISTFILE=~/.zsh_history
HISTSIZE=10000
HIST_STAMPS="dd-mm-yyyy"
SAVEHIST=10000

setopt HIST_VERIFY
#setopt SHARE_HISTORY # share history between sessions ???
setopt EXTENDED_HISTORY # add timestamps to history

# show slash at cd
zstyle ':completion:*' special-dirs true

# ssh
export SSH_KEY_PATH="~/.ssh/id_rsa"

function glog () {
    git log -p -40 $1 | vim - -R -c "set foldmethod=syntax"
}

# Lazy loading: https://github.com/kubernetes/kubernetes/issues/59078#issuecomment-363384825
function kubectl() {
    if ! type __start_kubectl >/dev/null 2>&1; then
        source <(command kubectl completion zsh)
    fi

    command kubectl "$@"
}

# Always use 256 colors with tmux
if [[ -r $(which tmux-next) ]]; then
    alias tmux="tmux-next -2"
else
    alias tmux="tmux -2"
fi

unalias mv
unalias rm
unalias cp

unsetopt share_history

# Include if there is local aliases
if [[ -a ~/.aliases_local ]]; then
    source ~/.aliases_local
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export PATH="/usr/local/opt/mysql-client/bin:$PATH"

# To customize prompt, run `p10k configure` or edit ~/Private/dotfiles/zsh/p10k.zsh.
[[ ! -f ~/Private/dotfiles/zsh/p10k.zsh ]] || source ~/Private/dotfiles/zsh/p10k.zsh
