export PATH=$HOME/bin:/usr/local/bin:$PATH

if [ -d "$HOME/.local/bin" ]; then
    export PATH="$HOME/.local/bin:$PATH";
fi

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

[[ $TMUX = "" ]] && export TERM="xterm-256color"

# Make sure the following packages are installed: fonts-powerline fonts-font-awesome texlive-fonts-extra
#POWERLEVEL9K_MODE='awesome-patched'
#POWERLEVEL9K_MODE='awesome-'

# Disable dir/git icons
POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''

# disable tags
POWERLEVEL9K_VCS_HIDE_TAGS=true

POWERLEVEL9K_CONTEXT_TEMPLATE="%n"

DISABLE_AUTO_TITLE="true"

POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_VCS_STAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_UNTRACKED_ICON='\u25CF'
POWERLEVEL9K_VCS_UNSTAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\u2193'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\u2191'

POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='yellow'

POWERLEVEL9K_SHORTEN_DIR_LENGTH=4

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs root_indicator)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(custom_semver custom_docker custom_aws custom_proxy)

POWERLEVEL9K_CUSTOM_SEMVER="zsh_semver"
POWERLEVEL9K_CUSTOM_SEMVER_BACKGROUND="yellow"
POWERLEVEL9K_CUSTOM_SEMVER_FOREGROUND="black"
POWERLEVEL9K_CUSTOM_DOCKER="zsh_docker"
POWERLEVEL9K_CUSTOM_DOCKER_BACKGROUND="blue"
POWERLEVEL9K_CUSTOM_DOCKER_FOREGROUND="white"
POWERLEVEL9K_CUSTOM_AWS="zsh_aws"
POWERLEVEL9K_CUSTOM_AWS_BACKGROUND="red"
POWERLEVEL9K_CUSTOM_AWS_FOREGROUND="white"
POWERLEVEL9K_CUSTOM_PROXY="zsh_proxy"
POWERLEVEL9K_CUSTOM_PROXY_BACKGROUND="magenta"
POWERLEVEL9K_CUSTOM_PROXY_FOREGROUND="white"
ZSH_THEME="powerlevel9k/powerlevel9k"

zsh_semver() {
    if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]]; then
        local tag
        tag=$(git describe --tags --exact-match HEAD 2>/dev/null)
        if [[ $tag =~ "^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$" ]]; then
            echo -n "$tag"
        fi
    fi
}

zsh_docker() {
    local docker_host="$DOCKER_MACHINE_NAME"

    if [[ -n "$docker_host" ]]; then
        echo -n 🐳 "$docker_host"
    fi
}

# AWS Profile
zsh_aws() {
  local aws_profile="$AWS_PROFILE"

  if [[ -n "$aws_profile" ]]; then
  	echo -n "AWS: $aws_profile"
  fi
}

# Show if proxy on/off
zsh_proxy() {
    local proxy="$http_proxy"
    if [[ -n "$proxy" ]]; then
        echo -n "Proxy: ON"
    else
        echo -n "Proxy: OFF"
    fi
}

# oh-my-zsh settings
DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="false"

# CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"
# export UPDATE_ZSH_DAYS=13
#DISABLE_AUTO_TITLE="true"
# COMPLETION_WAITING_DOTS="true"

plugins=(git common-aliases docker jump terraform gradle)

source $ZSH/oh-my-zsh.sh

# User configuration
export EDITOR='vim'
export VISUAL='vim'

# history settings
HISTFILE=~/.zsh_history
HISTSIZE=10000
HIST_STAMPS="dd-mm-yyyy"
SAVEHIST=10000

setopt HIST_VERIFY
#setopt SHARE_HISTORY # share history between sessions ???
setopt EXTENDED_HISTORY # add timestamps to history

# show slash at cd
zstyle ':completion:*' special-dirs true

# ssh
export SSH_KEY_PATH="~/.ssh/id_rsa"

function glog () {
    git log -p -40 $1 | vim - -R -c "set foldmethod=syntax"
}

# Always use 256 colors with tmux
if [[ -r $(which tmux-next) ]]; then
    alias tmux="tmux-next -2"
else
    alias tmux="tmux -2"
fi

unalias mv
unalias rm
unalias cp

unsetopt share_history

# Include if there is local aliases
if [[ -a ~/.aliases_local ]]; then
    source ~/.aliases_local
fi
